#!/bin/bash

if [ "$NOLINT" == "1" ] || [ "$NOLINT" == true ]; then exit 0; fi

# Get Odoo version to check (normally comes from .travis.cfg)
export TRAVIS_FILE=`pwd -P`/.travis.yml
if [ -f ${TRAVIS_FILE} ]; then
    echo "reading ${TRAVIS_FILE}"
    export VERSION=`grep VERSION .travis.yml | sed -n 's;.*VERSION="\([^"]*\).*;\1;p'`
    echo "Testing with version: $VERSION"
else
    echo "Cannot determine the odoo version as ${TRAVIS_FILE} is missing"
fi

set -v

FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"

flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg
status1=$?
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
status2=$?

TRAVIS_PULL_REQUEST="true" TRAVIS_BRANCH="HEAD" TRAVIS_BUILD_DIR=`pwd -P` $(dirname $0)/test_pylint
pylint_status=$?
exit $((${status1} || ${status2} || ${pylint_status}))
